import type { PhotoMeta } from '../types'

/**
 * KUNYE
 * Eser adi, yeri ve hikayesi burada durur. `npm run photos` bu dosyayi ASLA
 * ezmez; yalnizca yeni eklenen fotograflar icin bos satir acar.
 *
 * Bos birakilan alanlar otomatik degerlere duser (baslik = dosya adi,
 * yil = EXIF cekim tarihi). Bos hikaye kunyede hic gosterilmez.
 */
export const photoMeta: Record<string, PhotoMeta> = {
  'img-1082': { title: '', place: '', story: '' },
  'img-2820': { title: '', place: '', story: '' },
  'img-3452': { title: '', place: '', story: '' },
  'img-4538': { title: '', place: '', story: '' },
  'img-4893': { title: '', place: '', story: '' },
  'img-5346': { title: '', place: '', story: '' },
  'img-6177': { title: '', place: '', story: '' },
  'img-7544': { title: '', place: '', story: '' },
  'img-8146': { title: '', place: '', story: '' },
  'img-8169': { title: '', place: '', story: '' },
  'img-8628': { title: '', place: '', story: '' },
  'img-1947': { title: '', place: '', story: '' },
  'img-2400': { title: '', place: '', story: '' },
  'img-2752': { title: '', place: '', story: '' },
  'img-2795': { title: '', place: '', story: '' },
  'img-2798': { title: '', place: '', story: '' },
  'img-2824': { title: '', place: '', story: '' },
  'img-3060': { title: '', place: '', story: '' },
  'img-3061': { title: '', place: '', story: '' },
  'img-3062': { title: '', place: '', story: '' },
  'img-3355': { title: '', place: '', story: '' },
  'img-3874': { title: '', place: '', story: '' },
  'img-3912': { title: '', place: '', story: '' },
  'img-4234': { title: '', place: '', story: '' },
  'img-4245': { title: '', place: '', story: '' },
  'img-4253': { title: '', place: '', story: '' },
  'img-4457': { title: '', place: '', story: '' },
  'img-4655': { title: '', place: '', story: '' },
  'img-4961': { title: '', place: '', story: '' },
  'img-5148': { title: '', place: '', story: '' },
  'img-5175': { title: '', place: '', story: '' },
  'img-5180': { title: '', place: '', story: '' },
  'img-5356': { title: '', place: '', story: '' },
  'img-5498': { title: '', place: '', story: '' },
  'img-5520': { title: '', place: '', story: '' },
  'img-5521': { title: '', place: '', story: '' },
  'img-5851': { title: '', place: '', story: '' },
  'img-5964': { title: '', place: '', story: '' },
  'img-5972': { title: '', place: '', story: '' },
  'img-5975': { title: '', place: '', story: '' },
  'img-5976': { title: '', place: '', story: '' },
  'img-6383': { title: '', place: '', story: '' },
  'img-6605': { title: '', place: '', story: '' },
  'img-8153': { title: '', place: '', story: '' },
  'img-8656': { title: '', place: '', story: '' },
  'img-1070': { title: '', place: '', story: '' },
  'img-1077': { title: '', place: '', story: '' },
  'img-2790': { title: '', place: '', story: '' },
  'img-2863': { title: '', place: '', story: '' },
  'img-3011': { title: '', place: '', story: '' },
  'img-3014': { title: '', place: '', story: '' },
  'img-3015': { title: '', place: '', story: '' },
  '19c3f410-e800-41c2-a610-8b8f829c6bf5': { title: '', place: '', story: '' },
  'img-3059': { title: '', place: '', story: '' },
  'img-3062-1': { title: '', place: '', story: '' },
  '306cf0d0-6575-4258-9206-0bbeddfad7fa': { title: '', place: '', story: '' },
  'img-3094': { title: '', place: '', story: '' },
  'img-3157': { title: '', place: '', story: '' },
  'img-3372': { title: '', place: '', story: '' },
  'img-4147': { title: '', place: '', story: '' },
  '84e7ab8c-ad07-4f8d-b37f-71d0f814784e': { title: '', place: '', story: '' },
  'img-4375': { title: '', place: '', story: '' },
  'img-4663': { title: '', place: '', story: '' },
  'img-4684': { title: '', place: '', story: '' },
  'img-4692': { title: '', place: '', story: '' },
  'img-4697': { title: '', place: '', story: '' },
  '7c05f0f9-584a-4306-b597-92ff66591815': { title: '', place: '', story: '' },
  'img-4700': { title: '', place: '', story: '' },
  'img-4702': { title: '', place: '', story: '' },
  'img-4705': { title: '', place: '', story: '' },
  'img-4706': { title: '', place: '', story: '' },
  'img-4707': { title: '', place: '', story: '' },
  'img-4720': { title: '', place: '', story: '' },
  'img-4722': { title: '', place: '', story: '' },
  'img-4743': { title: '', place: '', story: '' },
  'img-4861': { title: '', place: '', story: '' },
  'img-2760': { title: '', place: '', story: '' },
  'img-2834': { title: '', place: '', story: '' },
  'img-3845': { title: '', place: '', story: '' },
  'img-4329': { title: '', place: '', story: '' },
  'img-4480': { title: '', place: '', story: '' },
  'img-4619': { title: '', place: '', story: '' },
  'img-4847': { title: '', place: '', story: '' },
  'img-5105': { title: '', place: '', story: '' },
  'img-5168': { title: '', place: '', story: '' },
  'img-5460': { title: '', place: '', story: '' },
  'img-5561': { title: '', place: '', story: '' },
  'img-5649': { title: '', place: '', story: '' },
  'a684645c-3c5a-40c6-9c97-697f183036c3': { title: '', place: '', story: '' },
  'img-4770': { title: '', place: '', story: '' },
  '7952a751-b35b-46b9-a78c-65c56b8c8b64': { title: '', place: '', story: '' },
  'img-4782': { title: '', place: '', story: '' },
  'whatsapp-image-2026-08-30-at-18-39-54': { title: '', place: '', story: '' },
  'whatsapp-image-2026-08-30-at-18-39-54-1': { title: '', place: '', story: '' },
  'whatsapp-image-2026-08-30-at-18-39-54-2': { title: '', place: '', story: '' },
  'whatsapp-image-2026-08-30-at-18-39-54-3': { title: '', place: '', story: '' },
  'whatsapp-image-2026-08-30-at-18-39-55': { title: '', place: '', story: '' },
  'whatsapp-image-2026-08-30-at-18-39-55-1': { title: '', place: '', story: '' },
  'whatsapp-image-2026-08-30-at-18-39-55-2': { title: '', place: '', story: '' },
  'img-6033': { title: '', place: '', story: '' },
}
