import type { PhotoMeta } from '../types'

/**
 * KUNYE
 * Eser adi, yeri ve hikayesi burada durur. `npm run photos` bu dosyayi ASLA
 * ezmez; yalnizca yeni eklenen fotograflar icin bos satir acar.
 *
 * Bos birakilan alanlar otomatik degerlere duser (baslik = dosya adi,
 * yil = EXIF cekim tarihi). Bos hikaye kunyede hic gosterilmez.
 */
export const photoMeta: Record<string, PhotoMeta> = {
  'img-1082': { title: 'Çanakkale kütüphanesi', place: '', story: '' },
  'img-2820': { title: 'Gelibolu seyir terası', place: '', story: '' },
  'img-3452': { title: 'Günbatımı', place: '', story: '' },
  'img-4538': { title: 'Sıcak, rustik, nostaljik', place: '', story: '' },
  'img-4893': { title: 'Günbatımı', place: '', story: '' },
  'img-5346': { title: 'Raf bulutu', place: '', story: 'güçlü bir gök gürültülü fırtınanın (kümülonimbüs) hemen ön kenarında, alçak irtifada yatay bir kama şeklinde oluşur. Altından geçerken hava aniden soğur, rüzgar sertleşir ve arkasından yoğun bir sağanak yağış gelir.' },
  'img-6177': { title: 'Gelincik bebek', place: '', story: '' },
  'img-7544': { title: 'Sakarya yolu', place: '', story: '' },
  'img-8146': { title: 'Sapanca sahili', place: '', story: '' },
  'img-8169': { title: 'Gözyaşı havuzu', place: '', story: '' },
  'img-8628': { title: 'Günbatımı', place: '', story: '' },
  'img-1947': { title: 'Dağ Lalesi', place: '', story: 'Koparmanın cezası 699 bin tl olan nadir tür.' },
  'img-2400': { title: 'Alifuatpaşa tren yolu', place: '', story: '' },
  'img-2752': { title: 'İzmir Çeşme Kalesi', place: '', story: '' },
  'img-2795': { title: 'Alaçatı Camii', place: '', story: 'Eski adıyla Ayios Konstantinos Kilisesi' },
  'img-2798': { title: 'Alaçatı', place: '', story: '' },
  'img-2824': { title: 'Etnik figürler', place: '', story: '' },
  'img-3060': { title: 'Beraber yaşlanmak güzeldir; kırışan ellerde değil, aynı denize bakan gözlerde birleşir ömür.', place: '', story: '-Özdemir Asaf' },
  'img-3061': { title: 'Hüsnüyusuf Çiçekleri', place: '', story: '' },
  'img-3062': { title: '', place: '', story: '' },
  'img-3355': { title: 'Dizilmiş yavru kediler', place: '', story: '' },
  'img-3874': { title: '', place: '', story: '' },
  'img-3912': { title: 'Pembe güller', place: '', story: '' },
  'img-4234': { title: 'Japon Bahçesi', place: '', story: '' },
  'img-4245': { title: 'Mirketler', place: '', story: '' },
  'img-4253': { title: 'Filamingolar', place: '', story: '' },
  'img-4457': { title: 'Kıvırcık marul tarlası', place: '', story: '' },
  'img-4655': { title: 'Yavru av köpeği', place: '', story: '' },
  'img-4961': { title: '', place: '', story: '' },
  'img-5148': { title: 'Şemsiyeli Kadın', place: '', story: '' },
  'img-5175': { title: 'Doğal taşlar', place: '', story: '' },
  'img-5180': { title: 'Tablolar ve minyatürler', place: '', story: '' },
  'img-5356': { title: 'Zürafa', place: '', story: 'Dilleri mor siyah renktedir ve koyu renkli melanin pigmenti sayesinde UV ışınlarına karşı vücutlarının diğer tüm kısımlarından çok daha korunaklıdır.' },
  'img-5498': { title: 'Mudanya', place: '', story: '' },
  'img-5520': { title: 'Rüzgar Çanları', place: '', story: '' },
  'img-5521': { title: 'Mudanya', place: '', story: '' },
  'img-5851': { title: 'Tren Garı', place: '', story: '' },
  'img-5964': { title: '', place: '', story: '' },
  'img-5972': { title: 'Kabak Çiçeği (dişi)', place: '', story: '' },
  'img-5975': { title: 'Zinya çiçeği', place: '', story: '' },
  'img-5976': { title: 'Yıldız patı', place: '', story: '' },
  'img-6383': { title: '', place: '', story: '' },
  'img-6605': { title: 'Yüksek kümülüs bulutları', place: '', story: '' },
  'img-8153': { title: '', place: '', story: '' },
  'img-8656': { title: 'Karanfiller', place: '', story: '' },
  'img-1070': { title: 'Eses', place: '', story: '' },
  'img-1077': { title: 'Platin saçlı at', place: '', story: '' },
  'img-2790': { title: 'Çuha çiçeği', place: '', story: '' },
  'img-2863': { title: 'Sakura', place: '', story: 'Japon kiraz çiçeği' },
  'img-3011': { title: 'Chihuahua', place: '', story: '' },
  'img-3014': { title: '', place: '', story: '' },
  'img-3015': { title: 'Bütün kapılarımı kapatmıştım sana, ama tabiat yine de eşiğimi çiçeklerle sarmış; senin geleceğin günün baharıymış meğer.', place: '', story: '' },
  '19c3f410-e800-41c2-a610-8b8f829c6bf5': { title: 'Blush, Sauvignon Blanc, Şiraz, Tenedos, Cabernet Sauvignon', place: '', story: '' },
  'img-3059': { title: 'Seramik atölyesi', place: '', story: '' },
  'img-3062-1': { title: '', place: '', story: '' },
  '306cf0d0-6575-4258-9206-0bbeddfad7fa': { title: '', place: '', story: '' },
  'img-3094': { title: 'Bozcaada', place: '', story: '' },
  'img-3157': { title: 'Rhizostoma pulmo', place: '', story: 'Oluklu denizanası zehirlidir.' },
  'img-3372': { title: '🎵Sende Kalmış', place: '', story: '' },
  'img-4147': { title: 'Çanakkale Boğazı', place: '', story: '' },
  '84e7ab8c-ad07-4f8d-b37f-71d0f814784e': { title: 'Eses', place: '', story: '' },
  'img-4375': { title: 'Sarmaşıklı geçit', place: '', story: '' },
  'img-4663': { title: 'Büyükpark', place: '', story: '' },
  'img-4684': { title: 'Pargalı burayı bırakıp nasıl Manisayı düşündün...', place: '', story: '' },
  'img-4692': { title: 'Huzur salonu', place: '', story: 'Dolmabahçe' },
  'img-4697': { title: 'Topkapı Sara', place: '', story: '' },
  '7c05f0f9-584a-4306-b597-92ff66591815': { title: 'Topkapı bahçe', place: '', story: '' },
  'img-4700': { title: '', place: '', story: '' },
  'img-4702': { title: 'Yakın Doğu ve Hitit sanatı', place: '', story: '' },
  'img-4705': { title: 'Mezapotamya uygarlığı rahibe', place: '', story: '' },
  'img-4706': { title: 'Sfenks', place: '', story: '' },
  'img-4707': { title: 'Lahit', place: '', story: '' },
  'img-4720': { title: 'Dolmabahçe ana salon', place: '', story: '' },
  'img-4722': { title: 'Dolmabahçe', place: '', story: '' },
  'img-4743': { title: 'Dolmabahçe bahçesi', place: '', story: '' },
  'img-4861': { title: '', place: '', story: '' },
  'img-2760': { title: 'Martıların kapışması', place: '', story: '' },
  'img-2834': { title: 'Kilitbahir', place: '', story: '' },
  'img-3845': { title: 'İskele', place: '', story: '' },
  'img-4329': { title: 'Güzelyalı', place: '', story: '' },
  'img-4480': { title: 'Marteniçka', place: '', story: '' },
  'img-4619': { title: 'Özbek', place: '', story: '' },
  'img-4847': { title: 'Wisteria', place: '', story: '' },
  'img-5105': { title: '', place: '', story: '' },
  'img-5168': { title: '57. alay', place: '', story: '' },
  'img-5460': { title: '', place: '', story: '' },
  'img-5561': { title: 'Bozcaada', place: '', story: '' },
  'img-5649': { title: 'Sandal', place: '', story: '' },
  'a684645c-3c5a-40c6-9c97-697f183036c3': { title: 'Hatime Ana Ulu Camii', place: '', story: '' },
  'img-4770': { title: 'Abdülmecidin tadına varamadan göçtüğü hazine boşaltan manzara...', place: '', story: '' },
  '7952a751-b35b-46b9-a78c-65c56b8c8b64': { title: 'Yerebatan sarnıcı', place: '', story: '' },
  'img-4782': { title: '', place: '', story: '' },
  'whatsapp-image-2026-08-30-at-18-39-54': { title: '', place: '', story: '' },
  'whatsapp-image-2026-08-30-at-18-39-54-1': { title: 'Manga', place: '', story: '' },
  'whatsapp-image-2026-08-30-at-18-39-54-2': { title: '', place: '', story: '' },
  'whatsapp-image-2026-08-30-at-18-39-54-3': { title: '', place: '', story: '' },
  'whatsapp-image-2026-08-30-at-18-39-55': { title: '', place: '', story: '' },
  'whatsapp-image-2026-08-30-at-18-39-55-1': { title: '', place: '', story: '' },
  'whatsapp-image-2026-08-30-at-18-39-55-2': { title: 'İngiliz seter-Pointer', place: '', story: '' },
  'img-6033': { title: 'Kordon', place: '', story: '' },
}
